if: tag IS blank
os: linux
dist: bionic
language: java
jdk: openjdk13
env: MAVEN_VERSION=3.6.3
install: true
script:
  - ./forkmc build

before_deploy:
  - export TRAVIS_TAG="$TRAVIS_BUILD_NUMBER"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: ./ForkMC-Proxy/bootstrap/target/ForkMC.jar
  on:
    repo: ForkMC/Fork-Proxy
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: ForkMC Build $TRAVIS_BUILD_NUMBER
  edge: true

cache:
  directories:
    - $HOME/.m2
